First regression test.
FAIL!

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -32,8 +32,10 @@ lib: $(soname)
 progs:$(PROGS)
 
 
-clean:
-	rm -f tests/*.result tests/*.test tests/*.result_ $(PROGS) *.o src/*.o *.so.*
+clean: testclean
+	rm -f $(PROGS) *.o src/*.o *.so.*
+testclean:
+	rm -f tests/*.result tests/*.test tests/*.result_ 
 
 all: lib progs test doc
 
@@ -105,10 +107,8 @@ tests/results:$(TEST_RESULT)
 
 #Build a test executable from a test program. On compile error,
 #create an executable which declares the error.
-tests/%.test: tests/%.cc
-	$(CXX) $(CXXFLAGS) $< -o $@ -I . $(LDFLAGS) ||\ { \ echo "echo 'Compile error!' ; return 126" > $@ ; \
-	  chmod +x $@; \
-	}
+tests/%.test: tests/%.cc $(LIBOBJS)
+	$(CXX) $(CXXFLAGS) $^ -o $@ -I . $(LDFLAGS) $(LOADLIBES) || {  echo "echo 'Compile error!' ; return 126" > $@ ; chmod +x $@; }
 
 #Run the program and either use it's output (it should just say OK)
 #or a failure message
@@ -117,7 +117,7 @@ tests/%.result_: tests/%.test
 	a=$$? ;\
 	if [ $$a != 0 ]; \
 	then \
-	   if [ $$a -ge 128 and ] ; \
+	   if [ $$a -ge 128 ] ; \
 	   then \
 	       echo Crash!! > $@ ; \
 	   elif [ $$a -ne 126 ] ;\
